"""chain anchors for hash ledger

Revision ID: 56cb0dcb2672
Revises: ed4c52fdcfac
Create Date: 2026-09-11 19:09:35.727178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cb0dcb2672'
down_revision = 'ed4c52fdcfac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_anchors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('head_hash', sa.String(length=64), nullable=False),
    sa.Column('chain_digest', sa.String(length=64), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('anchored_by', sa.UUID(), nullable=False),
    sa.Column('anchored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['anchored_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chain_anchors')
    # ### end Alembic commands ###
