"""add police rank, view-only flag, account provenance

Revision ID: 5c223f6a4c09
Revises: e5b0cc79a386
Create Date: 2026-09-10 21:24:04.320480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c223f6a4c09'
down_revision = 'e5b0cc79a386'
branch_labels = None
depends_on = None


police_rank_enum = sa.Enum(
    'CONSTABLE', 'HEAD_CONSTABLE', 'ASSISTANT_SUB_INSPECTOR', 'SUB_INSPECTOR',
    'INSPECTOR', 'DEPUTY_SUPERINTENDENT', 'SUPERINTENDENT',
    'DEPUTY_INSPECTOR_GENERAL', 'INSPECTOR_GENERAL', 'COMMISSIONER',
    'DIRECTOR_GENERAL', name='police_rank',
)


def upgrade() -> None:
    # op.add_column() does NOT create a native enum type the way create_table()
    # does, so the type has to be created first or the ALTER TABLE fails with
    # 'type "police_rank" does not exist'.
    police_rank_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rank', sa.Enum('CONSTABLE', 'HEAD_CONSTABLE', 'ASSISTANT_SUB_INSPECTOR', 'SUB_INSPECTOR', 'INSPECTOR', 'DEPUTY_SUPERINTENDENT', 'SUPERINTENDENT', 'DEPUTY_INSPECTOR_GENERAL', 'INSPECTOR_GENERAL', 'COMMISSIONER', 'DIRECTOR_GENERAL', name='police_rank'), server_default='SUB_INSPECTOR', nullable=False))
    op.add_column('users', sa.Column('is_view_only', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('station', sa.String(length=160), nullable=True))
    op.add_column('users', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key('users_created_by_id_fkey', 'users', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # The native enum type must be dropped explicitly; dropping the column
    # that uses it leaves the type behind and a re-upgrade then fails with
    # "type police_rank already exists".
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_created_by_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'created_by_id')
    op.drop_column('users', 'station')
    op.drop_column('users', 'is_view_only')
    op.drop_column('users', 'rank')
    sa.Enum(name='police_rank').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
