"""add live capture proof-of-presence to evidence

Revision ID: ed4c52fdcfac
Revises: 5c223f6a4c09
Create Date: 2026-09-10 21:32:41.372932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4c52fdcfac'
down_revision = '5c223f6a4c09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('live_capture_key', sa.String(length=512), nullable=True))
    op.add_column('evidence', sa.Column('live_capture_sha256', sa.String(length=64), nullable=True))
    op.add_column('evidence', sa.Column('live_capture_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence', 'live_capture_at')
    op.drop_column('evidence', 'live_capture_sha256')
    op.drop_column('evidence', 'live_capture_key')
    # ### end Alembic commands ###
